config/routes.rb
Rails.application.routes.draw do
  resources :routes
  root 'routes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: %i[ show edit update destroy ]

  # GET /routes or /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1 or /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes or /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to route_url(@route), notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to route_url(@route), notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy

    respond_to do |format|
      format.html { redirect_to routes_url, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def route_params
      params.require(:route).permit(:name, :location, :level, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>

  <div class="container">
    <%= yield %>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table class="table table-dark table-hover">

    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col">Level</th>
        <th scope="col">Comments</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>


    <tbody>
      <% @routes.each do |route| %>
        <tr>
          <td><%= route.name %></td>
          <td><%= route.location %></td>
          <td><%= route.level %></td>
          <td><%= route.comments %></td>
          <td><%= link_to 'Show', route %></td>
          <td><%= link_to 'Edit', edit_route_path(route) %></td>
          <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @route.location %>
</p>

<p>
  <strong>Level:</strong>
  <%= @route.level %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @route.comments %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>